// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Local dev uses `.env` (local Postgres via `prisma dev`). To run Prisma
// CLI commands against the production database, pass DATABASE_URL_UNPOOLED
// explicitly on the command line rather than auto-loading it here — this
// file intentionally does NOT auto-load any Vercel-managed env file, so a
// stray `.env.local` can never silently redirect local dev at the
// production database.

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI commands (migrate, db push, etc.) need a direct, unpooled
    // connection. The running app uses the pooled DATABASE_URL instead —
    // see src/lib/db.ts.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
